Add mkdir

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -167,6 +167,7 @@ jobs:
       - name: Copy docs from connectors repository
         run: |
           git clone --depth 1 https://.:${{ secrets.GITHUB_TOKEN }}@github.com/airbytehq/airbyte /tmp/airbyte_repo
+          mkdir -p ./docs
           cp -R /tmp/airbyte_repo/docs/integrations ./docs/integrations
           cp -R /tmp/airbyte_repo/docs/.gitbook ./docs/.gitbook
           [ -f "./docs/integrations/sources/google-ads.md" ] || { ls -Rlha ./docs; echo "::error ::Failed to copy docs from airbyte repository"; exit 21; }
@@ -289,6 +290,16 @@ jobs:
           org.gradle.workers.max=8
           org.gradle.vfs.watch=false
           EOF
+
+      # TODO: Once we pull these from the metadata service, remove this step. Also we can't build the webapp locally
+      #       since docs are not pulled when running gradle locally.
+      - name: Copy docs from connectors repository
+        run: |
+          git clone --depth 1 https://.:${{ secrets.GITHUB_TOKEN }}@github.com/airbytehq/airbyte /tmp/airbyte_repo
+          mkdir -p ./docs
+          cp -R /tmp/airbyte_repo/docs/integrations ./docs/integrations
+          cp -R /tmp/airbyte_repo/docs/.gitbook ./docs/.gitbook
+          [ -f "./docs/integrations/sources/google-ads.md" ] || { ls -Rlha ./docs; echo "::error ::Failed to copy docs from airbyte repository"; exit 21; }
 
       - name: Build Platform Docker Images
         run: SUB_BUILD=PLATFORM ./gradlew --no-daemon assemble --scan
